global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'act-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'act-prometheus:9090' ]

  - job_name: 'act-eureka'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-eureka:8761' ]

  - job_name: 'act-gateway'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-gateway:5000' ]

  - job_name: 'act-sessions'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-sessions:8081' ]

  - job_name: 'act-rooms'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-rooms:8082' ]

  - job_name: 'act-movies'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-movies:8083' ]

  - job_name: 'act-tickets'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-tickets:8084' ]

  - job_name: 'act-payments'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-payments:8085' ]
