global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'act-prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'act-prometheus:9090' ]

  - job_name: 'act-eureka'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'act-eureka:8761' ]
