spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: movies-service
          uri: lb://MOVIES-SERVICE
          predicates:
            - Path=/movies/**
        - id: tickets-service
          uri: lb://TICKETS-SERVICE
          predicates:
            - Path=/tickets/**

server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://act-eureka:8761/eureka/
  instance:
    hostname: act-gateway
