spring:
  application:
    name: payments-service
  rabbitmq:
    host: act-rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://act-eureka:8761/eureka/
  instance:
    hostname: act-payments
